{"name": "test_s1", "status": "broken", "statusDetails": {"message": "NameError", "trace": "self = <test_demo6.TestClass1 object at 0x03F8E0D0>\n\n    def test_s1(self):\n        print(\"用例 1：搜索 python-1\")\n        # 如果第一个用例异常了，不影响其他的用例执行\n>       raise NameError  # 模拟异常\nE       NameError\n\ntest_demo6.py:18: NameError"}, "start": 1615054278979, "stop": 1615054278979, "uuid": "48df14b9-3452-4992-aa20-d39a9cbdd606", "historyId": "493da83af498c042825d4db3188bf6d6", "fullName": "test_demo6.TestClass1#test_s1", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_demo6"}, {"name": "subSuite", "value": "TestClass1"}, {"name": "host", "value": "LHL"}, {"name": "thread", "value": "22228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo6"}]}