{"name": "test_s1", "status": "broken", "statusDetails": {"message": "NameError", "trace": "self = <test_demo5.TestClass1 object at 0x03F9BCF0>\n\n    def test_s1(self):\n        print(\"用例 1：搜索 python-1\")\n        # 如果第一个用例异常了，不影响其他的用例执行\n>       raise NameError  # 模拟异常\nE       NameError\n\ntest_demo5.py:17: NameError"}, "start": 1615054278965, "stop": 1615054278965, "uuid": "48f3b608-cc24-45b8-9f8d-d58210b0b7e5", "historyId": "a5882a2324dbadc6b8a4e626bf536af1", "fullName": "test_demo5.TestClass1#test_s1", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_demo5"}, {"name": "subSuite", "value": "TestClass1"}, {"name": "host", "value": "LHL"}, {"name": "thread", "value": "22228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo5"}]}